# SPDX-FileCopyrightText: 2025 Alec Delaney
# SPDX-License-Identifier: MIT

services:
  test-app:
    build:
      context: ../
      dockerfile: docker/app/Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - test-contrib:/app/assets/contrib
      - test-gh_cards:/app/flask_app/static/img/gh_cards
    depends_on:
      - test-cache
  test-cache:
    build:
      context: ../
      dockerfile: docker/cache/Dockerfile
      args:
        GRAPHQL_TOKEN: ${GRAPHQL_TOKEN}
    volumes:
      - test-contrib:/cache/assets/contrib
      - test-gh_cards:/cache/gh_cards
    env_file:
      - ../.env

volumes:
  test-contrib:
  test-gh_cards:
