# SPDX-FileCopyrightText: 2024 Alec Delaney
# SPDX-License-Identifier: MIT

name: Publish Test Site

on:
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  publish-test-website:
    runs-on: ubuntu-latest
    environment:
      name: testing
    steps:
    - name: Update and deploy on server
      uses: appleboy/ssh-action@v1.0.1
      with:
        host: tekktrik.dev
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Change to directory
          cd /srv/www/test-tekktrik-dev

          # Update the repository
          git fetch
          git checkout ${{ github.head_ref }}
          git config pull.rebase true
          git pull --rebase -ff

          # Update the environment
          rm -rf .venv
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          deactivate

          # Update image cache instruction
          sh scripts/schedule_cache.sh

          # Reload supervisor
          supervisorctl start test_flask_app
